import { FormEvent, useEffect, useState } from "react";
import { type LearningLevel, type LearningProfile, type UpdateLearningProfileInput } from "../../../../services/profile.service";
import "./LearningProfileSection.css";

const levels: Array<{ value: LearningLevel; label: string }> = [
  { value: "beginner", label: "Cơ bản" }, { value: "intermediate", label: "Trung cấp" }, { value: "advanced", label: "Nâng cao" },
];

export function LearningProfileSection({ profile, isLoading, onSave }: { profile: LearningProfile | null; isLoading: boolean; onSave: (input: UpdateLearningProfileInput) => Promise<void> }) {
  const [goal, setGoal] = useState(""); const [level, setLevel] = useState<LearningLevel | "">(""); const [hours, setHours] = useState(""); const [skill, setSkill] = useState(""); const [target, setTarget] = useState<LearningLevel>("intermediate"); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { setGoal(profile?.learningGoal ?? ""); setLevel(profile?.currentLevel ?? ""); setHours(profile?.weeklyAvailabilityHours?.toString() ?? ""); setSkill(profile?.skillGaps[0]?.name ?? ""); setTarget(profile?.skillGaps[0]?.targetLevel ?? "intermediate"); }, [profile]);
  async function submit(event: FormEvent) { event.preventDefault(); const value = hours.trim() ? Number(hours) : null; if (value !== null && (!Number.isInteger(value) || value < 1 || value > 168)) { setMessage("Số giờ mỗi tuần phải từ 1 đến 168."); return; } setSaving(true); setMessage(""); try { await onSave({ learningGoal: goal.trim() || null, currentLevel: level || null, weeklyAvailabilityHours: value, skillGaps: skill.trim() ? [{ name: skill.trim(), currentLevel: level || null, targetLevel: target }] : [] }); setMessage("Đã lưu định hướng học tập."); } catch { setMessage("Không thể lưu định hướng học tập."); } finally { setSaving(false); } }
  return <section className="learning-profile" aria-labelledby="learning-profile-title"><h2 id="learning-profile-title">Định hướng học tập</h2><form onSubmit={(event) => void submit(event)}><label>Mục tiêu học tập<textarea value={goal} maxLength={1000} onChange={(event) => setGoal(event.target.value)} disabled={isLoading || saving} /></label><label>Trình độ hiện tại<select value={level} onChange={(event) => setLevel(event.target.value as LearningLevel | "")} disabled={isLoading || saving}><option value="">Chưa chọn</option>{levels.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><label>Số giờ mỗi tuần<input inputMode="numeric" value={hours} onChange={(event) => setHours(event.target.value)} disabled={isLoading || saving} /></label><label>Kỹ năng muốn phát triển<input value={skill} maxLength={120} onChange={(event) => setSkill(event.target.value)} disabled={isLoading || saving} /></label><label>Mục tiêu kỹ năng<select value={target} onChange={(event) => setTarget(event.target.value as LearningLevel)} disabled={isLoading || saving}>{levels.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><button type="submit" disabled={isLoading || saving}>{saving ? "Đang lưu…" : "Lưu định hướng"}</button>{message ? <p role="status">{message}</p> : null}</form></section>;
}
