import { useEffect, useState } from "react";
import { mentorService, type MentorAvailability, type MentorProfile } from "../../services/mentor.service";
import "./mentors.css";

const days = ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm", "Thứ sáu", "Thứ bảy"];
const toTime = (minute: number) => `${String(Math.floor(minute / 60)).padStart(2, "0")}:${String(minute % 60).padStart(2, "0")}`;
const toMinute = (value: string) => { const [hour, minute] = value.split(":").map(Number); return hour * 60 + minute; };

export function InstructorMentorSettingsPage() {
  const [profile, setProfile] = useState<MentorProfile | null>(null); const [headline, setHeadline] = useState(""); const [bio, setBio] = useState(""); const [timezone, setTimezone] = useState(Intl.DateTimeFormat().resolvedOptions().timeZone || "UTC"); const [expertise, setExpertise] = useState(""); const [slots, setSlots] = useState<MentorAvailability[]>([{ dayOfWeek: 1, startMinute: 540, endMinute: 600 }]); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  useEffect(() => { mentorService.getMine().then((value) => { if (!value) return; setProfile(value); setHeadline(value.headline); setBio(value.bio || ""); setTimezone(value.timezone); setExpertise(value.expertise.map((item) => item.name).join(", ")); setSlots(value.availability.length ? value.availability : slots); }).catch((reason) => setError(reason instanceof Error ? reason.message : "Không thể tải hồ sơ.")); }, []);
  const changeSlot = (index: number, changes: Partial<MentorAvailability>) => setSlots((current) => current.map((slot, slotIndex) => slotIndex === index ? { ...slot, ...changes } : slot));
  async function save(event: React.FormEvent) { event.preventDefault(); try { const next = await mentorService.updateMine({ headline, bio: bio || null, timezone, expertise: expertise.split(",").map((value) => value.trim()).filter(Boolean), availability: slots }); setProfile(next); setError(""); setMessage("Đã lưu và gửi hồ sơ để xét duyệt."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Không thể lưu hồ sơ."); } }
  async function toggle() { if (!profile) return; try { setProfile(await mentorService.setActive(!profile.isActive)); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Không thể đổi trạng thái."); } }
  return <div className="mentor-page"><header><p>Mentor workspace</p><h1>Thiết lập hồ sơ cố vấn</h1><span>Lịch lặp lại được lưu theo múi giờ IANA của bạn.</span></header>{profile ? <p className="mentor-status">Xét duyệt: <strong>{profile.status}</strong> · Hiển thị: <strong>{profile.isActive ? "đang bật" : "đang tắt"}</strong></p> : null}<form className="mentor-form" onSubmit={save}><label>Tiêu đề chuyên môn<input required maxLength={160} value={headline} onChange={(event) => setHeadline(event.target.value)} /></label><label>Giới thiệu<textarea maxLength={2000} value={bio} onChange={(event) => setBio(event.target.value)} /></label><label>Múi giờ IANA<input required value={timezone} onChange={(event) => setTimezone(event.target.value)} /></label><label>Chuyên môn, phân cách bằng dấu phẩy<input value={expertise} onChange={(event) => setExpertise(event.target.value)} /></label><fieldset><legend>Lịch khả dụng hằng tuần</legend>{slots.map((slot, index) => <div className="mentor-slot" key={index}><select aria-label={`Ngày ${index + 1}`} value={slot.dayOfWeek} onChange={(event) => changeSlot(index, { dayOfWeek: Number(event.target.value) })}>{days.map((day, dayIndex) => <option key={day} value={dayIndex}>{day}</option>)}</select><input aria-label={`Bắt đầu ${index + 1}`} type="time" value={toTime(slot.startMinute)} onChange={(event) => changeSlot(index, { startMinute: toMinute(event.target.value) })} /><input aria-label={`Kết thúc ${index + 1}`} type="time" value={toTime(slot.endMinute)} onChange={(event) => changeSlot(index, { endMinute: toMinute(event.target.value) })} /><button onClick={() => setSlots((current) => current.filter((_, slotIndex) => slotIndex !== index))} type="button">Xóa</button></div>)}<button disabled={slots.length >= 30} onClick={() => setSlots((current) => [...current, { dayOfWeek: 1, startMinute: 540, endMinute: 600 }])} type="button">Thêm khung giờ</button></fieldset><button type="submit">Lưu hồ sơ</button></form>{profile?.status === "approved" ? <button className="mentor-toggle" onClick={() => void toggle()} type="button">{profile.isActive ? "Tắt mentor mode" : "Bật mentor mode"}</button> : null}{error ? <p role="alert">{error}</p> : null}{message ? <p role="status">{message}</p> : null}</div>;
}
