import { useEffect, useState } from "react";
import { mentorService, type MentorBooking, type MentorOutcome } from "../../services/mentor.service";

export function MentorOutcomePanel({ booking, mode, onCompleted }: { booking: MentorBooking; mode: "student" | "instructor"; onCompleted: () => Promise<void> }) {
  const [outcome, setOutcome] = useState<MentorOutcome | null>(null); const [error, setError] = useState("");
  async function load() { try { setOutcome(await mentorService.getOutcome(booking.id)); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Không thể tải kết quả cố vấn."); } }
  useEffect(() => { void load(); }, [booking.id]);
  async function saveNote(kind: "private" | "shared", event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const content = String(new FormData(event.currentTarget).get("content") || ""); try { await (kind === "private" ? mentorService.savePrivateNote(booking.id, content) : mentorService.saveSharedNote(booking.id, content)); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Không thể lưu ghi chú."); } }
  async function createGoal(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const content = String(new FormData(event.currentTarget).get("content") || ""); try { await mentorService.createGoal(booking.id, content); event.currentTarget.reset(); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Không thể tạo mục tiêu."); } }
  async function saveReview(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await mentorService.saveReview(booking.id, Number(form.get("rating")), String(form.get("comment") || "") || undefined); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Không thể lưu đánh giá."); } }
  return <section className="mentor-outcome" aria-label="Kết quả cố vấn">{error ? <p role="alert">{error}</p> : null}<p>Đánh giá mentor: {outcome?.rating.average ?? "—"}/5 ({outcome?.rating.count ?? 0})</p>{outcome?.sharedNote ? <p><strong>Ghi chú chia sẻ:</strong> {outcome.sharedNote.content}</p> : null}{mode === "instructor" && outcome ? <><form onSubmit={(event) => void saveNote("private", event)}><label>Ghi chú riêng<textarea name="content" defaultValue={outcome.privateNote?.content ?? ""} required maxLength={5000} /></label><button type="submit">Lưu ghi chú riêng</button></form><form onSubmit={(event) => void saveNote("shared", event)}><label>Ghi chú chia sẻ<textarea name="content" defaultValue={outcome.sharedNote?.content ?? ""} required maxLength={5000} /></label><button type="submit">Lưu ghi chú chia sẻ</button></form><form onSubmit={(event) => void createGoal(event)}><input name="content" required maxLength={500} placeholder="Bước tiếp theo" /><button type="submit">Thêm mục tiêu</button></form>{booking.status === "accepted" ? <button onClick={() => void mentorService.completeBooking(booking.id).then(onCompleted).catch((reason) => setError(reason instanceof Error ? reason.message : "Không thể hoàn tất."))} type="button">Hoàn tất buổi cố vấn</button> : null}</> : null}<ul>{outcome?.goals.map((item) => <li key={item.id}><span>{item.content}</span><button onClick={() => void mentorService.updateGoal(booking.id, item.id, item.status === "open" ? "completed" : "open").then(load)} type="button">{item.status === "open" ? "Đánh dấu hoàn thành" : "Mở lại"}</button></li>)}</ul>{mode === "student" && booking.status === "completed" ? <form onSubmit={(event) => void saveReview(event)}><label>Điểm<select name="rating" defaultValue={outcome?.review?.rating ?? 5}>{[5,4,3,2,1].map((value) => <option key={value} value={value}>{value}</option>)}</select></label><textarea name="comment" defaultValue={outcome?.review?.comment ?? ""} maxLength={2000} placeholder="Nhận xét" /><button type="submit">Lưu đánh giá</button><small>Đánh giá có thể chỉnh sửa trong 7 ngày.</small></form> : null}</section>;
}
