import { useEffect, useState } from "react";
import { mentorService, type MentorBooking } from "../../services/mentor.service";
import "./mentors.css";

const formatter = new Intl.DateTimeFormat("vi-VN", { dateStyle: "medium", timeStyle: "short" });

export function MentorBookingsPage({ mode }: { mode: "student" | "instructor" }) {
  const [items, setItems] = useState<MentorBooking[]>([]); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  async function load() { setLoading(true); try { const result = mode === "student" ? await mentorService.listStudentBookings() : await mentorService.listInstructorBookings(); setItems(result.items); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Không thể tải lịch cố vấn."); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [mode]);
  async function action(id: string, operation: "accept" | "reject" | "cancel", reason = "") { try { if (operation === "accept") await mentorService.acceptBooking(id); else if (operation === "reject") await mentorService.rejectBooking(id, reason); else await mentorService.cancelBooking(id, reason); await load(); } catch (reasonValue) { setError(reasonValue instanceof Error ? reasonValue.message : "Không thể cập nhật lịch."); } }
  async function reschedule(id: string, event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await mentorService.rescheduleBooking(id, new Date(String(form.get("start"))).toISOString(), new Date(String(form.get("end"))).toISOString()); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Không thể đổi lịch."); } }
  return <div className="mentor-page"><header><p>Canonical schedule</p><h1>{mode === "student" ? "Lịch cố vấn của tôi" : "Yêu cầu cố vấn"}</h1><span>Hai bên cùng xem một thời gian UTC canonical, hiển thị theo múi giờ thiết bị.</span></header>{loading ? <p role="status">Đang tải…</p> : null}{error ? <p role="alert">{error}</p> : null}<section className="mentor-bookings">{items.map((booking) => <article key={booking.id}><span>{booking.status}</span><h2>{mode === "student" ? booking.mentorProfile?.user.fullName : booking.student?.fullName}</h2><h3>{booking.topic}</h3><time dateTime={booking.scheduledStart}>{formatter.format(new Date(booking.scheduledStart))}</time><span>→ {formatter.format(new Date(booking.scheduledEnd))}</span><small>{booking.history.length} thay đổi trạng thái</small>{booking.cancellationReason ? <p>Lý do hủy: {booking.cancellationReason}</p> : null}{["requested", "reschedule_requested"].includes(booking.status) ? <form onSubmit={(event) => { event.preventDefault(); const reason = String(new FormData(event.currentTarget).get("reason") || "Không phù hợp lịch đề xuất"); void action(booking.id, "reject", reason); }}><input name="reason" placeholder="Lý do nếu từ chối" minLength={3} /><button onClick={() => void action(booking.id, "accept")} type="button">Chấp nhận</button><button type="submit">Từ chối</button></form> : null}{booking.status === "accepted" ? <form onSubmit={(event) => void reschedule(booking.id, event)}><input aria-label="Bắt đầu mới" name="start" type="datetime-local" required /><input aria-label="Kết thúc mới" name="end" type="datetime-local" required /><button type="submit">Đề xuất đổi lịch</button></form> : null}{["requested", "accepted", "reschedule_requested"].includes(booking.status) ? <form onSubmit={(event) => { event.preventDefault(); void action(booking.id, "cancel", String(new FormData(event.currentTarget).get("reason") || "")); }}><input name="reason" placeholder="Lý do hủy" required minLength={3} /><button type="submit">Hủy lịch</button></form> : null}</article>)}</section></div>;
}
