import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { mentorService, type MentorPage } from "../../services/mentor.service";
import "./mentors.css";

export function MentorDirectoryPage() {
  const [result, setResult] = useState<MentorPage | null>(null); const [search, setSearch] = useState(""); const [expertise, setExpertise] = useState(""); const [page, setPage] = useState(1); const [error, setError] = useState("");
  const [message, setMessage] = useState("");
  useEffect(() => { mentorService.list({ page, search: search || undefined, expertise: expertise || undefined }).then(setResult).catch((reason) => setError(reason instanceof Error ? reason.message : "Không thể tải danh bạ.")); }, [page]);
  function submit(event: React.FormEvent) { event.preventDefault(); setPage(1); mentorService.list({ page: 1, search: search || undefined, expertise: expertise || undefined }).then(setResult).catch((reason) => setError(reason instanceof Error ? reason.message : "Không thể tìm kiếm.")); }
  async function request(mentorId: string, event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await mentorService.requestBooking(mentorId, { topic: String(form.get("topic") || ""), scheduledStart: new Date(String(form.get("start"))).toISOString(), scheduledEnd: new Date(String(form.get("end"))).toISOString() }); setMessage("Đã gửi yêu cầu đặt lịch."); setError(""); event.currentTarget.reset(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Không thể đặt lịch."); } }
  return <div className="mentor-page"><header><p>Mentor network</p><h1>Tìm cố vấn phù hợp</h1><span>Chỉ hiển thị giảng viên đã được duyệt và chủ động bật mentor mode.</span></header><Link to="/dashboard/mentor-bookings">Xem lịch cố vấn của tôi</Link><form className="mentor-search" onSubmit={submit}><input aria-label="Tìm cố vấn" placeholder="Tên hoặc chủ đề" value={search} onChange={(event) => setSearch(event.target.value)} /><input aria-label="Lọc chuyên môn" placeholder="Chuyên môn" value={expertise} onChange={(event) => setExpertise(event.target.value)} /><button type="submit">Tìm kiếm</button></form>{error ? <p role="alert">{error}</p> : null}{message ? <p role="status">{message}</p> : null}<section className="mentor-grid">{result?.items.map((mentor) => <article key={mentor.id}><span>{mentor.timezone}</span><h2>{mentor.user?.fullName}</h2><h3>{mentor.headline}</h3><p>{mentor.bio}</p><div>{mentor.expertise.map((item) => <em key={item.name}>{item.name}</em>)}</div><small>{mentor.availability.length} khung giờ hằng tuần</small><form className="mentor-booking-form" onSubmit={(event) => void request(mentor.id, event)}><input aria-label={`Chủ đề ${mentor.user?.fullName}`} name="topic" placeholder="Chủ đề trao đổi" required minLength={3} /><input aria-label={`Bắt đầu ${mentor.user?.fullName}`} name="start" type="datetime-local" required /><input aria-label={`Kết thúc ${mentor.user?.fullName}`} name="end" type="datetime-local" required /><button type="submit">Gửi yêu cầu</button></form></article>)}</section>{result && result.totalPages > 1 ? <nav className="mentor-pagination"><button disabled={page === 1} onClick={() => setPage((value) => value - 1)}>Trước</button><span>{page} / {result.totalPages}</span><button disabled={page === result.totalPages} onClick={() => setPage((value) => value + 1)}>Sau</button></nav> : null}</div>;
}
